### DISCUSSION TITLE
What dongle bluetooth do you suggest

### DISCUSSION THREAD

**Discussion by phid78** [NicoIIT/ha-ble-adv#41] [Q&A] [answered]
Hi @NicoIIT , 
I think about buying a bluetooth dongle to add to my Freebox (as HA is on a VM) since a long time to try to manage my Fan usable trough [Smart Light (V1.5.6)](https://apkpure.com/smart-light/ai.argrace.remotecontrol)  and a remote.
I found your repo and i hope this is the good "smart light" app (there is a lot of same name).
I found a lot of topic about bluetooth dongle, but i'm sure it's better to ask to the owner which one (maybe some), he suggest.
Thanks for you reply

**Comment by NicoIIT** [comment, marked as answer]
Hi @phid78,

First of all I confirm the `Smart Light` app is the good one, still not sure there are any user with this HA integration and in Beta so you may find bugs (that I will fix if any!).

Concerning the Bluetooth dongle:
* I have no particular model to recommend, the interfaces used are base Linux ones so they should support any model compatible with Linux
* Still I have no idea if you would be able to communicate with it while hosted on a Freebox VM (and I cannot test myself as I do not have a Freebox Delta but a good old Freebox Revolution :smile:)
* The dongle must be located at the same place than your HA, so maybe not the best place to communicate with your device
* The Bluetooth on Linux while used from a docker is not the most stable system I saw...

I would rather recommend to use an ESP32 such as the USB-C powered [ESP32-C3](https://fr.aliexpress.com/item/1005008212278653.html) (or [this one](https://fr.aliexpress.com/item/1005007685790119.html) with antenna if you are far from your device) with ESPHome [ble_adv_proxy](https://github.com/NicoIIT/esphome-ble_adv_proxy) component:
* this is guaranteed to work
* this is much more stable
* you can place the ESP32 where you want in your home (it communicates via Wifi with your HA), the nearest to your device the better.
* you can also install an ESPHome [bluetooth_proxy](https://esphome.io/components/bluetooth_proxy.html) on it to extend your HA with Standard Bluetooth LE features

Still it requires to learn how to use ESPHome...

**Comment by phid78** [comment]
Thanks for your quick answer, but i'm a noob, so ESP32 is like chinese language. 
To answer one question, my box is in the same room as the fan ;)
If i undrestand well, the esp32-C3 work like a dongle, i have to add a cable to connected to the usb dedicated to my HA of my box 
I think my VM has one port dedicated on my box and i have a bridge tuya on it, so i should buy a hub, no problem with it ?

If you think this is the best way, i'll follow your advise, but i'll probably need more help lol, maybe it's will be more easy by email if you want

**Comment by NicoIIT** [comment]
>Thanks for your quick answer, but i'm a noob, so ESP32 is like chinese language.

Indeed, this is a language to learn :rofl: 

>If i undrestand well, the esp32-C3 work like a dongle, i have to add a cable to connected to the usb dedicated to my HA of my box

Not exactly, an ESP32 is just a piece of hardware on which you can write IOT software. One utils to write software on it is [ESPHome](https://esphome.io/), it allows to turn your ESP32 into a smart object that you can very easily link to your HA:
* The first step is to write a yaml config (very basic info: a name, a board type, the wifi config of your network and the config of the ble_adv_proxy, I can help for that) and use ESPHome to convert it to software and upload it to your ESP32. This can be done with either:
    *  your ESP32 connected to your PC via USB-C and using Chrome and the dedicated [ESPHome web dashboard](https://web.esphome.io/)
    * your ESP32 connected to your Freebox (via USB-C for the first upload, then can be done via Wifi) and using the HA ESPHome add-on
* The next step is to link the ESP32 to your HA which should be quite automated as the ESP32 will automatically connect to your Wifi and should then be auto discovered by [HA ESPHome Integration](https://www.home-assistant.io/integrations/esphome/). For this it only needs to be powered by USB, either using a dedicated power supply or an USB port on your Freebox (or any other permanently powered USB port), but it will not need to communicate via USB.

>I think my VM has one port dedicated on my box and i have a bridge tuya on it, so i should buy a hub, no problem with it ?

No problem at all, you just need to power the ESP32 via USB, whatever USB-C, including an old phone power supply or a hub.

>If you think this is the best way

Well it is hard to say: if you do not feel confident with using ESPHome you can try with a Bluetooth Dongle but I cannot guarantee it will work so you may buy a dongle for nothing... But if it works it will be much easier than using an ESP32 (depending on your noob-level :smile:).

**Comment by phid78** [comment]
can you email me please, here is my email : ******@gmail.com i have some questions about hardware, it will be more easy in french thanks

EDIT: removing email

**Comment by phid78** [comment]
about the component, does it have to be put in a box? If i'm going to get a new component, it might as well be the best performing one. Although the box is in the same room as the fan, if I take this [component](https://fr.aliexpress.com/item/1005007685790119.html?spm=a2g0o.cart.0.0.42ae378dQARQnX&mp=1&pdp_npi=5%40dis%21EUR%21EUR%2011.22%21EUR%203.59%21%21EUR%203.55%21%21%21%40212e520f17467858236491064e5450%2112000041906328936%21ct%21FR%211883585022%21%211%210&gatewayAdapt=glo2fra) for extra range, where do I put the antenna? I don't suppose we're going to leave the components out in the open, or simply plug in the antenna and let it wander around? 
what do I do with the pin bars?
I think I saw that this component doesn't integrate the classic bluetooth, isn't there a component that integrates it too (the aim is not to have to buy another component if I need it later)
thanks for your reply

**Comment by phid78** [comment]
I just found back an [nrf 52840 dongle](https://www.nordicsemi.com/Products/Development-hardware/nRF52840-Dongle). does it have any interest here?

**Comment by NicoIIT** [comment]
@phid78 
* I do not communicate my email, nor you should, nor github does.
* I am not a Bluetooth hardware expert, I am a developer. If you found a dongle, just try it, but I will not answer any question such as "will this one work" because I do not know, especially from a VM in a Freebox.
* For the ESP32, mine is out in the open, but you can put it in a box it should not be an issue. And yes the latest version of those components only handle Bluetooth LE and not classic Bluetooth, so do not buy one for anything else than Bluetooth LE.

**Comment by phid78** [comment]
Don't worry about the e-mail address, it's a trash address.
You're right, sorry, I had a quick look on internet, and even if I don't master it, I think I understood that bluetooth mesh is different from Ble, so I'm going to buy what you recommended and if you don't mind, I'll come back to you if I can't get it.

**Comment by phid78** [comment]
Hi @NicoIIT, i received the item today, i've been on https://web.esphome.io/ to configure wifi, and now it's well connected to my box.
Now i suppose i have to add a yaml config. Looking at ESPHome [ble_adv_proxy](https://github.com/NicoIIT/esphome-ble_adv_proxy) component, i understand  it is this : 
```
logger:
  level: INFO

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esphome:
  name: esp32-idf

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

# Added for ble_adv_proxy
ble_adv_proxy:

external_components:
  source: github://NicoIIT/esphome-ble_adv_proxy
```


Am i correct ? because you talk also about wifi config 
Thanks for your reply

**Comment by NicoIIT** [comment]
As you already configured the ESP to connect to your box, you did 90% of the work already! 

You only need to add the part for ble_adv_proxy to your ESP32 config:

```yaml
ble_adv_proxy:

external_components:
  source: github://NicoIIT/esphome-ble_adv_proxy
```

Once done the next steps are on Home Assistant:
* Manually add the ESP with ESPHome integration if not already done by automatic detection
* Setup of the `ha-ble-adv` component and add an integration, following the doc / config flow. Please be aware of the [specificity](https://github.com/NicoIIT/ha-ble-adv?tab=readme-ov-file#when-i-try-to-add-an-integration-for-the-first-time-my-ble_adv_proxy-is-not-detected) for the first addition when using ble_adv_proxy

**Comment by phid78** [comment]
i have 2 errors : 
![image](https://github.com/user-attachments/assets/6f4e440e-e9e8-4d66-bdb1-8f6b18a03d20)

When i checked the web.esphome.io log : 
![image](https://github.com/user-attachments/assets/93b4ac30-df5e-490a-a8bf-5ac8487e4f37)

for info, i put the lines you gave me in a .txt, i call it ble.yaml and install through : 
![image](https://github.com/user-attachments/assets/03f9658f-ddb6-4004-a45d-85fa06afb424)

**Comment by NicoIIT** [comment]
Ah sorry I misunderstood your previous comment, you are not as advanced as I thought.

If your board is a "ESP32-C3 Super Mini" the config is the following, replacing <your_ssid> and <your_wifi_pwd> by your wifi parameters:

```yaml
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-c3.yaml@main

wifi:
  ssid: <your_ssid>
  password: <your_wifi_pwd>

ble_adv_proxy:

external_components:
  source: github://NicoIIT/esphome-ble_adv_proxy
```

If not please let me know I will prepare another config with the proper bluetooth-proxy link.

**Comment by phid78** [comment]
i probably do something wrong. I put the file you gave me in a blocnote sheet and save it as ble.yaml, then i click on install in web.esphome.io and choose this yaml. But i don't see it connected to wifi in my box setup page. 
Then, for another reason, i had to reboot my computeur and now, the usb device connect/deconnect, every second.
I saw on the web to push boot, hold, push rst and release rst then boot. now, the usb is well connected. I don't want to broke it , so i prefere to ask ;)

**Comment by NicoIIT** [comment]
I re did the same as you, meaning:
1. Copy the config in a ble.yaml file, **replacing the ssid / password with the ones of my wifi** between quotes:
```yaml
wifi:
  ssid: "this_is_my_ssid"
  password: "this_is_my_password"
```
3. Use it from web.esphome.io and installing as you did => It erased / installed it successfully
4. checking my wifi router, it is properly connected as "esp32-bluetooth-proxy-xxxxxx"

So I do not know what to say. Retry?

EDIT: WOOOOOOOOOOPS no in fact... the web interface requests a bin file, checking how to do that ...

EDIT2: in fact it is better for you to install the ESPHome device builder Home Assistant Add-on, as described here:
https://esphome.io/guides/getting_started_hassio.html

**Comment by phid78** [comment]
After a lot of try, (i probably do some bad thing), so i had to factory reset it. 
Now it seems to look good.
![image](https://github.com/user-attachments/assets/894636d5-da3c-43c3-8e1e-737efef72140)

log show : 
[19:45:12][I][logger:171]: Log initialized
[19:45:12][I][app:029]: Running through setup()...
[19:45:12][W][component:157]: Component wifi set Warning flag: scanning for networks
[19:45:15][I][wifi:541]: - 'monwifi' [redacted]▂▄▆█
[19:45:15][I][wifi:313]: WiFi Connecting to 'monwifi'...
[19:45:17][W][wifi_esp32:569][arduino_events]: Event: Disconnected ssid='monwifi' bssid=[redacted] reason='Auth Expired'
[19:45:17][W][wifi:653]: Error while connecting to network.
[19:45:17][I][wifi:313]: WiFi Connecting to 'monwifi'...
[19:45:18][I][wifi:617]: WiFi Connected!
[19:45:18][I][app:062]: setup() finished successfully!
[19:45:18][W][component:172]: Component wifi cleared Warning flag
[19:45:18][W][component:157]: Component api set Warning flag: unspecified
[19:45:18][I][app:100]: ESPHome version 2025.4.2 compiled on May 20 2025, 18:45:56
[19:46:12][I][safe_mode:041]: Boot seems successful; resetting boot loop counter

it is well connected to my box

As yaml, i've got : 
```
esphome:
  name: esp32c3
  friendly_name: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  
esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

# Added for ble_adv_proxy
ble_adv_proxy:

external_components:
  source: github://NicoIIT/esphome-ble_adv_proxy

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3 Fallback Hotspot"
    password: "XXXXXXXXX"

captive_portal:
    
```

In your readme for esphome-ble_adv_proxy, you recommand to change : 
```
esp32:
  board: esp32dev
  framework:
    type: esp-idf
```
Do i have to do also here or now i follow ha-ble-adv readme ?

**Reply by NicoIIT** [reply]
Yes I recommend to change the framework type, but keep the board as is:
```yaml
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
```

You can also put the log as DEBUG so that we can check them if needed for further debug:
```yaml
logger:
  level: DEBUG
```

Before starting the ha-ble-adv config, be sure to have an auto discovered Bluetooth Integration in Home Assistant referencing the name of your proxy "esp32c3".

**Comment by phid78** [comment]
Thank for your quick help, now i'm at the step to pair it, but light doesn't blink, i'll continue to test tomorrow

**Comment by NicoIIT** [comment]
If you have already paired with "Smart Light" Phone App you do not need to pair with HA: just use the first option to duplicate the config. Just for Smart Light App there are several control mode from the phone app and you must NOT use the "Master control", but the individual control: if you do not see the "Pair" and "Unpair" buttons at the bottom then your are not on the relevant place.

**Comment by phid78** [comment]
Sorry, I had an internet outage, and since my VM is on the box, no more Home Assistant (I really need to find how to migrate it to a mini PC).
I managed to pair the app and the remote control. I get the update in Home Assistant when I use them (so it's receiving fine), even if it sometimes lose certain commands along the way (if they are too close). However, I can't control them from Home Assistant (it doesn't transmit order).

**Comment by NicoIIT** [comment]
The first question is: did you manage to have the `Duplicate config` to work (make the light blink) ? 
Could you also confirm you are NOT using the `Master Control` part of the phone app ?

Have you tried to put your ESP (even temporarily, just to test) near the light, I mean less than 3m and in direct view (no wall), to be sure the problem is not the Bluetooth range of the ESP?

If there is no improvement, then it means the encoding may not be correct and it is a possibility as this one is still in BETA (no one tested it yet to my knowledge with ha-ble-adv)

EDIT: I also delivered release v1.0.8 including an attempt to solve a potential issue, but no guarantee.

**Comment by phid78** [comment]
I confirm that I use the application via the specific control of the fan, moreover to pair I pressed pair and I did the same by pressing pair on the remote control. And the light flashed
i configured like this : 
![image](https://github.com/user-attachments/assets/46609e28-d398-45d5-bbbe-33f156fe3b11)
![image](https://github.com/user-attachments/assets/8dff4ca8-2c73-44df-b164-683bb84fefb9)

There were 2 updates today for ESP, so I launched the updates on the ESP and your integration (I am now on 1.0.8). At the end of the last ESP update i try to send some command from my phone and from HA, here is what i get : 
![image](https://github.com/user-attachments/assets/8071588c-51cf-4ce9-bcbd-19c63a5a8d50)
each time i pushed a button (on phone or HA) a new line came, so i suppose order is send well
For information :
- when i log on mobile i get a message : HTTP 502
- when i push a button i'm close to the ESP and from my phone and the remote, it work on the device. (i'll try to be more closer from the device as you recommand)

**Reply by phid78** [reply]
I deleted and reconfigured it only via the app (not the remote wich is more used by us everyday, so maybe i had to configure only the remote)
I put the ESP underneath, and I can control it, but with latency and probably loss of control. I put it back, and it's the same, even though I feel like there's more loss and latency. Btw, nothing update on the app.
I'm in training this weekend, so I won't be able to try again; I'll try again on Monday.
In the meantime, here's a home assistant log, if it helps:
```
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.ble_adv.coordinator
Source: custom_components/ble_adv/coordinator.py:189
intégration: BLE ADV Ceiling Fan / Lamps (documentation, problèmes)
S'est produit pour la première fois: 21:14:57 (2 occurrences)
Dernier enregistrement: 21:16:27

[esp32c3] Exception handling raw adv message
Traceback (most recent call last):
  File "/config/custom_components/ble_adv/coordinator.py", line 189, in handle_raw_adv
    await device_callback.handle(codec_id, adapter_id, conf, ent_attrs)
  File "/config/custom_components/ble_adv/device.py", line 199, in handle
    await self.async_on_command(ent_attrs)
  File "/config/custom_components/ble_adv/device.py", line 309, in async_on_command
    ent.apply_attrs(ent_attr)
    ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/config/custom_components/ble_adv/fan.py", line 131, in apply_attrs
    recv_speed_count = self._get_speed_count_from_type(ent_attr.attrs[ATTR_SUB_TYPE])
                                                       ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'sub_type'
```

I have a question : to avoid listening to all the Bluetooth, is it not possible to give it only one mac address to listen to ?

**Reply by NicoIIT** [reply]
> I put the ESP underneath, and I can control it

Great, so we know the whole HA+ESP is working OK, and that you managed to have a proper config working. 

You can try to increase the Bluetooth range of the ESP with option `use_max_tx_power` (see ble_adv_proxy doc)

> with latency and probably loss of control

You will have to be more clear what you mean by latency (0.1s, 1s, 10s, ...) and by 'loss of control'... Maybe open a detailed bug report for this

> nothing update on the app.

I suppose you are talking about the phone app: yes it is normal as the phone app is not listening to traffic so not able to update itself when another controller is updating the device, as HA or the remote...

> here's a home assistant log, if it helps

This is a bug, corrected in release v1.0.9

> is it not possible to give it only one mac address to listen to 

I do not understand the question: which mac address do you want to listen to ?
* The one of the device: the device is not emitting anything so there is nothing to listen
* The one of your phone: it changes often for privacy purposes
* The one of the remote: this one is probably fixed, but what is the use? When you link the remote we listen to its (codec / ID / index) that uniquely identifies it so what would be the purpose to also filter by MAC address?

I thought about blacklisting MAC addresses to avoid spam logs, but they are there only in DEBUG, and in any case those ones are rejected quite fast.

I think this discussion is going far from its initial purpose (add a Bluetooth adapter). Should you have any other issues this should go via detailed [Bug Report](https://github.com/NicoIIT/ha-ble-adv/issues/new?template=bug.yml) so that I have all info needed to investigate.

**Comment by phid78** [comment]
Yes, you're right, i will close this one, but first of all, i'd like to thank you very much for your time, reactivity, and help to a noob ;)
I was trying to increase bluetooth range just after sending the mail, but too tired to continue, i'll finish on monday
MAc adress was to avoir spam log, and you just answered for this. About latency and other i'll open a new report if needed.
if i can help you to test whatever on my VM, just tell me.

**Comment by phid78** [comment]
As I was running tests (I hadn't paid attention to the Esp home update and the resulting bug), I tried to reconfigure some components, but at the end I lost everything.
So I'm starting from scratch, i'm currently in  2025.6.2 Esp Home version, I had to reinistiallised esp32, inject this config, except that I have a doubt, if we had put or not this line, so i test some version
```
packages:
esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-c3.yaml@main
```
Finally, at the end of the installation, I have an error message about the resolution of the IP. 
While searching, I saw that I had to add: 
use_address: 192.168.0.6 to the wifi info.
I didn't have this before, so is it due to the ESP Home update or a bad configuration of my ESP32?
Here it is:

```
esphome:
  name: esp32c3
  friendly_name: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

# Added for ble_adv_proxy
ble_adv_proxy:
  use_max_tx_power: true

external_components:
  source: github://NicoIIT/esphome-ble_adv_proxy

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-c3.yaml@main

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.0.6

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3 Fallback Hotspot"
    password: "xxxxxx"

captive_portal:
```
In esphome log, i get a warning : WARNING Found and merged multiple configurations for ota platform esphome port(s) [3232]
except that I've only got an esp32, so I'm thinking there's a typo.
apart from that, esp 32 doesn't report any error messages, so I try to integrate BLE ADV Ceiling Fan / Lamps but at the first stage it doesn't find anything when I press pair on the smart light application.
