### ISSUE TITLE
ble_adv working only on Linux Host even if BT Stack not used

### ISSUE THREAD

**Issue by NicoIIT** [NicoIIT/ha-ble-adv#31]
### Discussed in https://github.com/NicoIIT/ha-ble-adv/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **lexcao** April 22, 2025</sup>
First of all, thanks for the great idea and great work!

### Background
I am new to HA and ESPHome.
What I have currently archived:
1. Bought an ESP32
2. Finish setup ESPHome
3. Finish setup ESP32 with https://github.com/NicoIIT/esphome-ble_adv_proxy
  - the ESP is online
  - the ESP works fine, I can see the BT messages from logs
4. Finish connect `ble_adv_proxy` into HA
<img width="720" alt="image" src="https://github.com/user-attachments/assets/95f21600-a8c9-482e-ac0e-d34ada62df2e" />

### System

I am using MacOS 
```
Darwin 24.4.0 x86_64 i386
```
I am running HA and ESPHome via docker-compose.yml as following:
```
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    extra_hosts:
      - "esp32.local:192.168.50.66"
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ./esp_config:/config
    restart: unless-stopped
    network_mode: host
```

### Need Help
**I cannot add integration for `ble_adv`, I haved attached the logs in the bottom.**
<img width="720" alt="image" src="https://github.com/user-attachments/assets/4a0fc624-e918-4d22-b3e4-aff88916ddbf" />

### Error logs
The logs from HA are:
```
homeassistant  | 2025-04-23 01:50:10.807 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration ble_adv - received exception
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in async_setup_component
homeassistant  |     await future
homeassistant  |   File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in async_setup_component
homeassistant  |     await future
homeassistant  |   File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in async_setup_component
homeassistant  |     result = await _async_setup_component(hass, domain, config)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/setup.py", line 422, in _async_setup_component
homeassistant  |     result = await task
homeassistant  |              ^^^^^^^^^^
homeassistant  |   File "/config/custom_components/ble_adv/__init__.py", line 46, in async_setup
homeassistant  |     await get_coordinator(hass)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/singleton.py", line 67, in async_wrapped
homeassistant  |     result = await func(hass)
homeassistant  |              ^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/ble_adv/__init__.py", line 40, in get_coordinator
homeassistant  |     await coordinator.async_init()
homeassistant  |   File "/config/custom_components/ble_adv/coordinator.py", line 98, in async_init
homeassistant  |     await self._bt_manager.async_init()
homeassistant  |   File "/config/custom_components/ble_adv/adapters/__init__.py", line 435, in async_init
homeassistant  |     fileno = await self._mgmt_sock.async_init("mgmt", self._mgmt_recv, self._mgmt_close, True)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/ble_adv/async_socket/__init__.py", line 60, in async_init
homeassistant  |     return await self._async_open_socket(name, *args)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/ble_adv/async_socket/__init__.py", line 136, in _async_open_socket
homeassistant  |     self._socket = btmgmt_socket.open()
homeassistant  |                    ~~~~~~~~~~~~~~~~~~^^
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/btsocket/btmgmt_socket.py", line 59, in open
homeassistant  |     raise BluetoothSocketError("Unable to open PF_BLUETOOTH socket")
homeassistant  | btsocket.btmgmt_socket.BluetoothSocketError: Unable to open PF_BLUETOOTH socket
```</div>
